apiVersion: v1
kind: Namespace
metadata:
  name: status-service
  labels:
    app.kubernetes.io/name: status-service
    app.kubernetes.io/part-of: status-service
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
